### ISSUE TITLE
[myrequest] accepted  vazgeçme

### ISSUE THREAD

**Issue by hcoz** [hcoz/thelocalus#25]
adam bir kere accept ettiyse geri dönemeyecek mi la?
tamam söz vermek g.t vermeye benzemez ama o kadar da olmamalı bence :)

**Comment by fikrifirat** [comment]
ne diyecek o zaman? hover edince 'Change Response' yazsın ona mı tıklasın ?

28 Temmuz 2015 15:21 tarihinde Halil Can Özçelik <notifications@github.com>
yazdı:

**Comment by hcoz** [comment]
Beb arayüzü hallettim gerisi sende panpa. dosyanın başındaki ChangeResponse() fonksyonunda comment olarak yazdım el atacağın yerleri.

**Comment by fikrifirat** [comment]
ok.
