### ISSUE TITLE
guide profile da guide name çağıran fonksiyon eklenmemiş

### ISSUE THREAD

**Issue by hcoz** [hcoz/thelocalus#38]

**Comment by fikrifirat** [comment]
düzelttik lan ne bug mug diyon :) current_user almışım

**Comment by hcoz** [comment]
adam olcan yapmıycan öle hatalar :P

2015-08-16 10:54 GMT+03:00 fikrifirat <notifications@github.com>:

> Closed #38 <https://github.com/hcoz/thelocalus/issues/38>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hcoz/thelocalus/issues/38#event-383485209>.
>



-- 
*Halil Can Özçelik*
www.halilcanozcelik.com
